DOMAIN = "impc_energy"

BASE_ENERGY_API_URL = "http://yxwx.impc.com.cn"
BASE_APP_API_URL = "http://mdej.impc.com.cn"

UNIT_CURRENCY_YUAN = "元"
UNIT_KILOWATT_HOUR = "kWh"

ATTR_ACCOUNT_DATA = "account_data"
ATTR_ACCOUNT_NAME = "account_name"
ATTR_ACCOUNT_NUMBER = "account_number"
ATTR_BALANCE = "balance"
ATTR_BILL = "bill"
ATTR_CONFIG_MDEJ = "config_mdej"
ATTR_CONSUMPTION = "consumption"
ATTR_CURRENT = "current"
ATTR_DAILY = "daily"
ATTR_DATE = "date"
ATTR_DESC = "desc"
ATTR_HISTORY = "history"
ATTR_LOGIN_PAYLOAD = "login_payload"
ATTR_MONTH = "month"
ATTR_PASSWORD = "password"
ATTR_TOKEN = "token"
ATTR_USERNAME = "username"
