DOMAIN = "impc_energy"

BASE_ENERGY_API_URL = "https://yxwx.impc.com.cn"
BASE_APP_API_URL = "https://mdej.impc.com.cn"

UNIT_CURRENCY_YUAN = "元"
UNIT_KILOWATT_HOUR = "kWh"

ATTR_ACCOUNT_DATA = "account_data"
ATTR_ACCOUNT_NAME = "account_name"
ATTR_ACCOUNT_NUMBER = "account_number"
ATTR_BALANCE = "balance"
ATTR_BILL = "bill"
ATTR_CONFIG_MDEJ = "config_mdej"
ATTR_CONSUMPTION = "consumption"
ATTR_CURRENT = "current"
ATTR_DAILY = "daily"
ATTR_DATE = "date"
ATTR_DESC = "desc"
ATTR_HISTORY = "history"
ATTR_LOGIN_PAYLOAD = "login_payload"
ATTR_MONTH = "month"
ATTR_PASSWORD = "password"
ATTR_TOKEN = "token"
ATTR_USERNAME = "username"
ATTR_CURRENT_PRICE = "current_price"
ATTR_CURRENT_TIER = "current_tier"
ATTR_PRICE = "price"
ATTR_PRICE_CODE = "price_code"
ATTR_PRICE_NAME = "price_name"
ATTR_QUERY_MONTH = "query_month"
ATTR_TIER = "tier"
ATTR_TIER_NAME = "tier_name"
ATTR_TIERS = "tiers"
ATTR_TIERED_BILL = "tiered_bill"
ATTR_TIER_SPREAD_BILL = "tier_spread_bill"
ATTR_TOTAL_BILL = "total_bill"
ATTR_TOTAL_CONSUMPTION = "total_consumption"
